import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <AppSidebar />
          <div className="flex h-screen w-full overflow-hidden  border border-blue-400">
            {/* Make <main> flex so children can use min-h-0 */}
            <main className="flex-1 min-h-0">
              <SidebarTrigger />
              {/* keep the children in a column container if you like */}
              <div className="h-full min-h-0">{children}</div>
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
